#!/bin/bash
# Orc Verify Completion Hook
# Event: Stop
# Purpose: Forces the implement agent to re-verify spec and success criteria
# before completing. First stop is blocked with a re-verification prompt;
# second stop is allowed through.
#
# Uses a marker file to track state between invocations.
# Requires: jq
#
# Generated by orc - built-in hook script

set -euo pipefail

# Use task ID for marker uniqueness, fall back to session PID
MARKER_FILE="/tmp/orc-verify-completion-${ORC_TASK_ID:-$$}"

# Second stop attempt — allow it through
if [ -f "$MARKER_FILE" ]; then
    rm -f "$MARKER_FILE"
    exit 0
fi

# First stop attempt — block and force re-verification
touch "$MARKER_FILE"

cat <<'EOF'
BEFORE COMPLETING: Study the original specification and success criteria carefully. For each SC-X, verify you have implemented it and can point to the specific code that satisfies it. If this is a bug fix, grep for the buggy pattern across the entire codebase to ensure no instances were missed. Only stop when you have verified every criterion is met.
EOF
exit 2
