#!/bin/bash
# Orc TDD Discipline Hook
# Event: PreToolUse
# Matcher: Edit|Write|MultiEdit
# Purpose: During TDD phases, blocks non-test file writes to enforce
# test-first discipline.
#
# Requires: jq
#
# Generated by orc - built-in hook script

set -euo pipefail

HOOK_INPUT=$(cat)
TOOL_NAME=$(echo "$HOOK_INPUT" | jq -r '.tool_name // empty')

# Only intercept file-writing tools
case "$TOOL_NAME" in
    Write|Edit|MultiEdit) ;;
    *) exit 0 ;;
esac

FILE_PATH=$(echo "$HOOK_INPUT" | jq -r '.tool_input.file_path // empty')
if [ -z "$FILE_PATH" ]; then
    exit 0
fi

# Check if this is a test file
is_test_file() {
    case "$1" in
        *_test.go|*_test.py|*.test.ts|*.test.tsx|*.test.js|*.test.jsx|\
        *.spec.ts|*.spec.tsx|*.spec.js|*.spec.jsx)
            return 0 ;;
        *)
            return 1 ;;
    esac
}

if is_test_file "$FILE_PATH"; then
    exit 0
fi

# Block non-test file writes during TDD phase
echo "TDD discipline: During tdd_write phase, only test files can be modified. Blocked: $FILE_PATH"
echo "Write your tests first." >&2
exit 2
