#!/bin/bash
# Orc Verify Completion Hook
# Event: Stop (SessionEnd)
# Purpose: Validates that the phase produced proper completion JSON output.
#
# This hook runs at session end to verify the Claude session emitted
# a valid completion JSON block with {"status": "complete"|"blocked"|"continue"}.
# Without this, phases can silently fail to produce structured output.
#
# Generated by orc - built-in hook script

set -euo pipefail

# Read hook input from stdin
INPUT=$(cat)

# Extract the stop reason if available
STOP_REASON=$(echo "$INPUT" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get('stop_reason', ''))
except:
    print('')
" 2>/dev/null || echo "")

# Only validate on normal stop (not on error/timeout)
if [ "$STOP_REASON" = "error" ] || [ "$STOP_REASON" = "timeout" ]; then
    exit 0
fi

# Allow the session to end normally - verification happens at the executor level
exit 0
