#!/bin/bash
# Orc TDD Discipline Hook
# Event: PreToolUse
# Matcher: Edit|Write|MultiEdit
# Purpose: During TDD phases, reminds Claude to write tests before implementation.
#
# This hook intercepts file write operations during tdd_write phases
# and checks that test files are being written (not implementation files).
# It provides guidance rather than blocking — a "soft" enforcement.
#
# Generated by orc - built-in hook script

set -euo pipefail

# Read hook input from stdin
INPUT=$(cat)

# Extract tool name and file path
TOOL_NAME=$(echo "$INPUT" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get('tool_name', ''))
except:
    print('')
" 2>/dev/null || echo "")

FILE_PATH=$(echo "$INPUT" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    ti = data.get('tool_input', {})
    print(ti.get('file_path', ''))
except:
    print('')
" 2>/dev/null || echo "")

# Only check during TDD phase (indicated by env var)
if [ -z "${ORC_PHASE_TDD:-}" ]; then
    exit 0
fi

# Check if this is a test file
case "$FILE_PATH" in
    *_test.go|*_test.py|*.test.ts|*.test.tsx|*.test.js|*.spec.ts|*.spec.tsx|*.spec.js)
        # Writing test files is expected during TDD
        exit 0
        ;;
esac

# Non-test file during TDD phase — warn but allow
echo "⚠️  TDD Phase: Writing non-test file '$FILE_PATH'. Ensure tests are written first." >&2
exit 0
