<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import Icon from '$lib/components/ui/Icon.svelte';
	import {
		getSettings,
		getGlobalSettings,
		updateSettings,
		type Settings
	} from '$lib/api';

	// State
	let loading = $state(true);
	let saving = $state(false);
	let error = $state<string | null>(null);
	let success = $state<string | null>(null);

	// Settings
	let currentSettings = $state<Settings | null>(null);

	// Configuration mode: 'simple' for user-friendly UI, 'advanced' for raw script
	let configMode = $state<'simple' | 'advanced'>('simple');

	// Simple mode options
	let showUsername = $state(true);
	let showHostname = $state(true);
	let showDirectory = $state(true);
	let showGitBranch = $state(true);
	let showVirtualEnv = $state(true);
	let useColors = $state(true);
	let customPrefix = $state('');
	let customSuffix = $state('');

	// Advanced mode
	let rawCommand = $state('');
	let scriptPath = $state('');

	// Get scope from URL params
	const scope = $derived($page.url.searchParams.get('scope') as 'global' | 'project' | null);
	const isGlobal = $derived(scope === 'global');
	const settingsPath = $derived(isGlobal ? '~/.claude/settings.json' : '.claude/settings.json');
	const scriptDir = $derived(isGlobal ? '~/.claude' : '.claude');

	onMount(async () => {
		await loadSettings();
	});

	async function loadSettings() {
		try {
			loading = true;
			const settings = isGlobal ? await getGlobalSettings() : await getSettings();
			currentSettings = settings;

			if (settings?.statusLine?.command) {
				rawCommand = settings.statusLine.command;
				// Try to detect if it's a script path or inline command
				if (settings.statusLine.command.endsWith('.sh') ||
					settings.statusLine.command.startsWith('/') ||
					settings.statusLine.command.startsWith('~')) {
					scriptPath = settings.statusLine.command;
					configMode = 'advanced';
				} else {
					configMode = 'advanced';
				}
				// Try to parse existing script to populate simple mode options
				parseExistingConfig(settings.statusLine.command);
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load settings';
		} finally {
			loading = false;
		}
	}

	function parseExistingConfig(command: string) {
		// Basic heuristics to detect what's in the existing config
		// This is best-effort - complex scripts may not parse correctly
		const lower = command.toLowerCase();
		showUsername = lower.includes('whoami') || lower.includes('user') || lower.includes('\\u');
		showHostname = lower.includes('hostname') || lower.includes('\\h');
		showDirectory = lower.includes('pwd') || lower.includes('basename') || lower.includes('\\w');
		showGitBranch = lower.includes('git') && lower.includes('branch');
		showVirtualEnv = lower.includes('virtual_env');
		useColors = lower.includes('\\033') || lower.includes('\\e[');
	}

	// Generate the statusline script based on simple mode options
	function generateScript(): string {
		const parts: string[] = [];

		// Script header
		parts.push('#!/bin/bash');
		parts.push('# Claude Code statusline - generated by orc');
		parts.push('');

		// Helper variables using bash builtins (fast)
		if (showDirectory) {
			parts.push('cwd="$PWD"');
			parts.push('dir_basename="${cwd##*/}"');
		}
		if (showUsername) {
			parts.push('user_name="$USER"');
		}
		if (showHostname) {
			parts.push('host_name="${HOSTNAME%%.*}"');
		}
		parts.push('');

		// Build output parts
		const outputParts: string[] = [];

		// Custom prefix
		if (customPrefix.trim()) {
			if (useColors) {
				outputParts.push(`printf '\\033[90m${escapeForPrintf(customPrefix.trim())}\\033[0m '`);
			} else {
				outputParts.push(`printf '${escapeForPrintf(customPrefix.trim())} '`);
			}
		}

		// Virtual environment
		if (showVirtualEnv) {
			parts.push('# Virtual environment');
			parts.push('venv_info=""');
			parts.push('if [[ -n "$VIRTUAL_ENV" ]]; then');
			parts.push('    venv_name="${VIRTUAL_ENV##*/}"');
			if (useColors) {
				parts.push(`    venv_info=$(printf '\\033[38;5;214m(%s)\\033[0m ' "$venv_name")`);
			} else {
				parts.push(`    venv_info="($venv_name) "`);
			}
			parts.push('fi');
			parts.push('');
			outputParts.push('"$venv_info"');
		}

		// User@host
		if (showUsername && showHostname) {
			parts.push('# User and hostname');
			if (useColors) {
				parts.push(`user_host=$(printf '[\\033[32m%s\\033[0m:\\033[34m%s\\033[0m]' "$user_name" "$host_name")`);
			} else {
				parts.push(`user_host="[$user_name:$host_name]"`);
			}
			parts.push('');
			outputParts.push('"$user_host"');
		} else if (showUsername) {
			parts.push('# Username');
			if (useColors) {
				parts.push(`user_info=$(printf '[\\033[32m%s\\033[0m]' "$user_name")`);
			} else {
				parts.push(`user_info="[$user_name]"`);
			}
			parts.push('');
			outputParts.push('"$user_info"');
		} else if (showHostname) {
			parts.push('# Hostname');
			if (useColors) {
				parts.push(`host_info=$(printf '[\\033[34m%s\\033[0m]' "$host_name")`);
			} else {
				parts.push(`host_info="[$host_name]"`);
			}
			parts.push('');
			outputParts.push('"$host_info"');
		}

		// Git branch
		if (showGitBranch) {
			parts.push('# Git branch');
			parts.push('git_branch=""');
			if (showDirectory) {
				parts.push('if [[ -n "$cwd" ]] && git -C "$cwd" rev-parse --git-dir >/dev/null 2>&1; then');
				parts.push('    branch=$(git -C "$cwd" symbolic-ref --short HEAD 2>/dev/null)');
			} else {
				parts.push('if git rev-parse --git-dir >/dev/null 2>&1; then');
				parts.push('    branch=$(git symbolic-ref --short HEAD 2>/dev/null)');
			}
			parts.push('    if [[ -n "$branch" ]]; then');
			if (useColors) {
				parts.push(`        git_branch=$(printf ':\\033[38;5;244m%s\\033[0m' "$branch")`);
			} else {
				parts.push(`        git_branch=":$branch"`);
			}
			parts.push('    fi');
			parts.push('fi');
			parts.push('');
			outputParts.push('"$git_branch"');
		}

		// Directory
		if (showDirectory) {
			parts.push('# Current directory');
			if (useColors) {
				parts.push(`dir_info=$(printf ':\\033[35m%s\\033[0m' "$dir_basename")`);
			} else {
				parts.push(`dir_info=":$dir_basename"`);
			}
			parts.push('');
			outputParts.push('"$dir_info"');
		}

		// Custom suffix
		if (customSuffix.trim()) {
			if (useColors) {
				outputParts.push(`$(printf ' \\033[90m${escapeForPrintf(customSuffix.trim())}\\033[0m')`);
			} else {
				outputParts.push(`' ${escapeForPrintf(customSuffix.trim())}'`);
			}
		}

		// Final output
		parts.push('# Output');
		if (outputParts.length > 0) {
			parts.push(`printf '%s' ${outputParts.join(' ')}`);
		} else {
			parts.push('printf ""');
		}
		parts.push('');

		return parts.join('\n');
	}

	function escapeForPrintf(str: string): string {
		return str.replace(/'/g, "'\\''").replace(/%/g, '%%');
	}

	// Generate inline command for simple configurations
	function generateInlineCommand(): string {
		const parts: string[] = [];

		if (customPrefix.trim()) {
			parts.push(customPrefix.trim());
		}

		if (showVirtualEnv) {
			if (useColors) {
				parts.push('$(if [ -n "$VIRTUAL_ENV" ]; then printf "\\033[38;5;214m(%s)\\033[0m " "${VIRTUAL_ENV##*/}"; fi)');
			} else {
				parts.push('$(if [ -n "$VIRTUAL_ENV" ]; then echo -n "(${VIRTUAL_ENV##*/}) "; fi)');
			}
		}

		if (showUsername && showHostname) {
			if (useColors) {
				parts.push('$(printf "[\\033[32m%s\\033[0m:\\033[34m%s\\033[0m]" "$USER" "${HOSTNAME%%.*}")');
			} else {
				parts.push('[$USER:${HOSTNAME%%.*}]');
			}
		} else if (showUsername) {
			if (useColors) {
				parts.push('$(printf "[\\033[32m%s\\033[0m]" "$USER")');
			} else {
				parts.push('[$USER]');
			}
		} else if (showHostname) {
			if (useColors) {
				parts.push('$(printf "[\\033[34m%s\\033[0m]" "${HOSTNAME%%.*}")');
			} else {
				parts.push('[${HOSTNAME%%.*}]');
			}
		}

		if (showGitBranch) {
			if (useColors) {
				parts.push('$(git rev-parse --git-dir >/dev/null 2>&1 && printf ":\\033[38;5;244m%s\\033[0m" "$(git symbolic-ref --short HEAD 2>/dev/null)")');
			} else {
				parts.push('$(git rev-parse --git-dir >/dev/null 2>&1 && echo -n ":$(git symbolic-ref --short HEAD 2>/dev/null)")');
			}
		}

		if (showDirectory) {
			if (useColors) {
				parts.push('$(printf ":\\033[35m%s\\033[0m" "${PWD##*/}")');
			} else {
				parts.push(':${PWD##*/}');
			}
		}

		if (customSuffix.trim()) {
			parts.push(customSuffix.trim());
		}

		return `echo -n '${parts.join('')}'`;
	}

	function getPreviewText(): string {
		// Generate a sample preview of what the statusline might look like
		const parts: string[] = [];

		if (customPrefix.trim()) {
			parts.push(customPrefix.trim());
		}
		if (showVirtualEnv) {
			parts.push('(venv)');
		}
		if (showUsername && showHostname) {
			parts.push('[user:hostname]');
		} else if (showUsername) {
			parts.push('[user]');
		} else if (showHostname) {
			parts.push('[hostname]');
		}
		if (showGitBranch) {
			parts.push(':main');
		}
		if (showDirectory) {
			parts.push(':project-name');
		}
		if (customSuffix.trim()) {
			parts.push(' ' + customSuffix.trim());
		}

		return parts.join('') || '(empty statusline)';
	}

	async function handleSave() {
		saving = true;
		error = null;
		success = null;

		try {
			let command: string;

			if (configMode === 'advanced') {
				command = rawCommand.trim();
			} else {
				// For simple mode, generate an inline command or script path
				command = generateInlineCommand();
			}

			// Get current settings to preserve other fields
			const existingSettings = isGlobal ? await getGlobalSettings() : await getSettings();

			const newSettings: Settings = {
				...existingSettings,
				statusLine: command ? {
					type: 'command',
					command: command
				} : undefined
			};

			await updateSettings(newSettings, isGlobal ? 'global' : undefined);
			currentSettings = newSettings;
			success = 'Statusline configuration saved successfully';
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save statusline configuration';
		} finally {
			saving = false;
		}
	}

	async function handleClear() {
		if (!confirm('Remove statusline configuration? This will disable the custom statusline.')) {
			return;
		}

		saving = true;
		error = null;
		success = null;

		try {
			const existingSettings = isGlobal ? await getGlobalSettings() : await getSettings();

			const newSettings: Settings = {
				...existingSettings,
				statusLine: undefined
			};

			await updateSettings(newSettings, isGlobal ? 'global' : undefined);
			currentSettings = newSettings;
			rawCommand = '';
			success = 'Statusline configuration removed';
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to remove statusline configuration';
		} finally {
			saving = false;
		}
	}

	function applyPreset(preset: string) {
		switch (preset) {
			case 'minimal':
				showUsername = false;
				showHostname = false;
				showDirectory = true;
				showGitBranch = true;
				showVirtualEnv = false;
				useColors = true;
				customPrefix = '';
				customSuffix = '';
				break;
			case 'standard':
				showUsername = true;
				showHostname = true;
				showDirectory = true;
				showGitBranch = true;
				showVirtualEnv = true;
				useColors = true;
				customPrefix = '';
				customSuffix = '';
				break;
			case 'developer':
				showUsername = false;
				showHostname = false;
				showDirectory = true;
				showGitBranch = true;
				showVirtualEnv = true;
				useColors = true;
				customPrefix = '';
				customSuffix = '';
				break;
			case 'plain':
				showUsername = true;
				showHostname = true;
				showDirectory = true;
				showGitBranch = true;
				showVirtualEnv = true;
				useColors = false;
				customPrefix = '';
				customSuffix = '';
				break;
		}
	}

	// Watch for scope changes
	$effect(() => {
		if (!loading) {
			loadSettings();
		}
	});
</script>

<svelte:head>
	<title>{isGlobal ? 'Global ' : ''}Statusline - orc</title>
</svelte:head>

<div class="statusline-page">
	<header class="page-header">
		<div class="header-content">
			<div>
				<h1>{isGlobal ? 'Global ' : ''}Statusline Configuration</h1>
				<p class="subtitle">Configure Claude Code's statusline in {settingsPath}</p>
			</div>
			<div class="header-actions">
				<div class="scope-toggle">
					<a href="/environment/claude/statusline" class="scope-btn" class:active={!isGlobal}>Project</a>
					<a href="/environment/claude/statusline?scope=global" class="scope-btn" class:active={isGlobal}>Global</a>
				</div>
			</div>
		</div>
	</header>

	{#if error}
		<div class="alert alert-error">
			<Icon name="error" size={16} />
			{error}
		</div>
	{/if}

	{#if success}
		<div class="alert alert-success">
			<Icon name="check" size={16} />
			{success}
		</div>
	{/if}

	{#if loading}
		<div class="loading">Loading statusline configuration...</div>
	{:else}
		<div class="statusline-layout">
			<!-- Mode Toggle -->
			<div class="mode-toggle">
				<button
					class="mode-btn"
					class:active={configMode === 'simple'}
					onclick={() => configMode = 'simple'}
				>
					<Icon name="sliders" size={16} />
					Simple Mode
				</button>
				<button
					class="mode-btn"
					class:active={configMode === 'advanced'}
					onclick={() => configMode = 'advanced'}
				>
					<Icon name="terminal" size={16} />
					Advanced Mode
				</button>
			</div>

			{#if configMode === 'simple'}
				<!-- Simple Mode UI -->
				<div class="config-panel">
					<div class="panel-section">
						<h3>Presets</h3>
						<div class="presets-grid">
							<button class="preset-btn" onclick={() => applyPreset('minimal')}>
								<span class="preset-name">Minimal</span>
								<span class="preset-preview">:main:project</span>
							</button>
							<button class="preset-btn" onclick={() => applyPreset('standard')}>
								<span class="preset-name">Standard</span>
								<span class="preset-preview">(venv)[user:host]:branch:dir</span>
							</button>
							<button class="preset-btn" onclick={() => applyPreset('developer')}>
								<span class="preset-name">Developer</span>
								<span class="preset-preview">(venv):main:project</span>
							</button>
							<button class="preset-btn" onclick={() => applyPreset('plain')}>
								<span class="preset-name">Plain (No Colors)</span>
								<span class="preset-preview">[user:host]:branch:dir</span>
							</button>
						</div>
					</div>

					<div class="panel-section">
						<h3>Components</h3>
						<div class="options-grid">
							<label class="option-item">
								<input type="checkbox" bind:checked={showUsername} />
								<span class="option-label">
									<Icon name="user" size={14} />
									Username
								</span>
								<span class="option-example">$USER</span>
							</label>

							<label class="option-item">
								<input type="checkbox" bind:checked={showHostname} />
								<span class="option-label">
									<Icon name="server" size={14} />
									Hostname
								</span>
								<span class="option-example">$HOSTNAME</span>
							</label>

							<label class="option-item">
								<input type="checkbox" bind:checked={showDirectory} />
								<span class="option-label">
									<Icon name="folder" size={14} />
									Current Directory
								</span>
								<span class="option-example">${'{PWD##*/}'}</span>
							</label>

							<label class="option-item">
								<input type="checkbox" bind:checked={showGitBranch} />
								<span class="option-label">
									<Icon name="git-branch" size={14} />
									Git Branch
								</span>
								<span class="option-example">main, feature/...</span>
							</label>

							<label class="option-item">
								<input type="checkbox" bind:checked={showVirtualEnv} />
								<span class="option-label">
									<Icon name="box" size={14} />
									Python Virtual Env
								</span>
								<span class="option-example">(venv)</span>
							</label>

							<label class="option-item">
								<input type="checkbox" bind:checked={useColors} />
								<span class="option-label">
									<Icon name="palette" size={14} />
									Use Colors
								</span>
								<span class="option-example">ANSI escape codes</span>
							</label>
						</div>
					</div>

					<div class="panel-section">
						<h3>Custom Text</h3>
						<div class="form-row">
							<div class="form-group">
								<label for="prefix">Prefix</label>
								<input
									id="prefix"
									type="text"
									bind:value={customPrefix}
									placeholder="e.g., [orc]"
								/>
							</div>
							<div class="form-group">
								<label for="suffix">Suffix</label>
								<input
									id="suffix"
									type="text"
									bind:value={customSuffix}
									placeholder="e.g., $"
								/>
							</div>
						</div>
					</div>

					<div class="panel-section">
						<h3>Preview</h3>
						<div class="preview-box">
							<span class="preview-label">Sample output:</span>
							<code class="preview-text">{getPreviewText()}</code>
						</div>
					</div>
				</div>
			{:else}
				<!-- Advanced Mode UI -->
				<div class="config-panel">
					<div class="panel-section">
						<h3>Command</h3>
						<p class="help-text">
							Enter a shell command or path to a script that outputs the statusline text.
							The command receives JSON context on stdin with model info, workspace, and token usage.
						</p>
						<textarea
							class="command-input"
							bind:value={rawCommand}
							placeholder={'e.g., ~/.claude/statusline-command.sh\nor\necho -n "$(git branch --show-current 2>/dev/null):$' + '{PWD##*/}"'}
							rows="6"
						></textarea>
					</div>

					<div class="panel-section">
						<h3>Available Context (JSON on stdin)</h3>
						<div class="context-info">
							<code class="context-example">{`{
  "model": { "name": "claude-3-5-sonnet", "display_name": "Claude 3.5 Sonnet" },
  "workspace": { "current_dir": "/path/to/project" },
  "context_window": { "context_window_size": 200000, "current_usage": {...} },
  "output_style": { "name": "normal" }
}`}</code>
							<p class="context-hint">
								Use <code>input=$(cat); echo "$input" | jq -r '.model.display_name'</code> to extract values.
							</p>
						</div>
					</div>

					<div class="panel-section">
						<h3>Tips</h3>
						<ul class="tips-list">
							<li>Use <code>printf</code> with ANSI codes for colors: <code>\033[32mgreen\033[0m</code></li>
							<li>For scripts, save to <code>{scriptDir}/statusline.sh</code> and reference the path</li>
							<li>Avoid slow commands - the statusline runs frequently</li>
							<li>Test your command in terminal first: <code>bash -c 'your-command'</code></li>
						</ul>
					</div>
				</div>
			{/if}

			<!-- Actions -->
			<div class="actions">
				<button class="btn btn-primary" onclick={handleSave} disabled={saving}>
					{saving ? 'Saving...' : 'Save Configuration'}
				</button>
				{#if currentSettings?.statusLine}
					<button class="btn btn-secondary" onclick={handleClear} disabled={saving}>
						Remove Statusline
					</button>
				{/if}
			</div>

			<!-- Current Configuration Info -->
			{#if currentSettings?.statusLine}
				<div class="current-config">
					<h3>Current Configuration</h3>
					<div class="config-detail">
						<span class="detail-label">Type:</span>
						<code>{currentSettings.statusLine.type || 'command'}</code>
					</div>
					<div class="config-detail">
						<span class="detail-label">Command:</span>
						<code class="command-value">{currentSettings.statusLine.command}</code>
					</div>
				</div>
			{/if}
		</div>
	{/if}
</div>

<style>
	.statusline-page {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		max-width: 800px;
	}

	.page-header h1 {
		margin: 0;
		font-size: 1.5rem;
	}

	.header-content {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
	}

	.header-actions {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	.scope-toggle {
		display: flex;
		background: var(--bg-tertiary, rgba(0, 0, 0, 0.05));
		border-radius: 6px;
		padding: 2px;
	}

	.scope-btn {
		padding: 0.375rem 0.75rem;
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-secondary);
		text-decoration: none;
		border-radius: 4px;
		transition: all 0.15s ease;
	}

	.scope-btn:hover {
		color: var(--text-primary);
	}

	.scope-btn.active {
		background: var(--bg-primary);
		color: var(--text-primary);
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
	}

	.subtitle {
		margin: 0.5rem 0 0;
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.alert {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.75rem 1rem;
		border-radius: 6px;
		font-size: 0.875rem;
	}

	.alert-error {
		background: var(--error-bg, #fee2e2);
		color: var(--error-text, #dc2626);
		border: 1px solid var(--error-border, #fecaca);
	}

	.alert-success {
		background: var(--success-bg, #dcfce7);
		color: var(--success-text, #16a34a);
		border: 1px solid var(--success-border, #bbf7d0);
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}

	.statusline-layout {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	/* Mode Toggle */
	.mode-toggle {
		display: flex;
		gap: 0.5rem;
		padding: 0.25rem;
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		width: fit-content;
	}

	.mode-btn {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 1rem;
		background: transparent;
		border: none;
		border-radius: 6px;
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-secondary);
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.mode-btn:hover {
		color: var(--text-primary);
		background: var(--bg-tertiary);
	}

	.mode-btn.active {
		background: var(--primary, #3b82f6);
		color: white;
	}

	/* Config Panel */
	.config-panel {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		overflow: hidden;
	}

	.panel-section {
		padding: 1.25rem;
		border-bottom: 1px solid var(--border-color);
	}

	.panel-section:last-child {
		border-bottom: none;
	}

	.panel-section h3 {
		margin: 0 0 0.75rem;
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--text-primary);
	}

	/* Presets Grid */
	.presets-grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 0.5rem;
	}

	.preset-btn {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		gap: 0.25rem;
		padding: 0.75rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		cursor: pointer;
		text-align: left;
		transition: all 0.15s ease;
	}

	.preset-btn:hover {
		border-color: var(--primary, #3b82f6);
		background: var(--bg-tertiary);
	}

	.preset-name {
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-primary);
	}

	.preset-preview {
		font-size: 0.75rem;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		color: var(--text-secondary);
	}

	/* Options Grid */
	.options-grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 0.5rem;
	}

	.option-item {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.625rem 0.75rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.option-item:hover {
		border-color: var(--primary, #3b82f6);
	}

	.option-item input[type="checkbox"] {
		width: 1rem;
		height: 1rem;
		accent-color: var(--primary, #3b82f6);
	}

	.option-label {
		display: flex;
		align-items: center;
		gap: 0.375rem;
		flex: 1;
		font-size: 0.875rem;
		color: var(--text-primary);
	}

	.option-example {
		font-size: 0.75rem;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		color: var(--text-muted);
	}

	/* Form Elements */
	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.375rem;
	}

	.form-group label {
		font-size: 0.75rem;
		font-weight: 500;
		color: var(--text-secondary);
	}

	.form-group input {
		padding: 0.5rem 0.75rem;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		font-size: 0.875rem;
		background: var(--bg-primary);
		color: var(--text-primary);
	}

	.form-group input:focus {
		outline: none;
		border-color: var(--primary, #3b82f6);
	}

	/* Preview */
	.preview-box {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding: 0.75rem 1rem;
		background: var(--bg-tertiary);
		border-radius: 6px;
	}

	.preview-label {
		font-size: 0.75rem;
		color: var(--text-secondary);
		white-space: nowrap;
	}

	.preview-text {
		flex: 1;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.875rem;
		color: var(--text-primary);
		background: transparent;
		padding: 0;
	}

	/* Advanced Mode */
	.command-input {
		width: 100%;
		padding: 0.75rem;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.875rem;
		background: var(--bg-primary);
		color: var(--text-primary);
		resize: vertical;
		line-height: 1.5;
	}

	.command-input:focus {
		outline: none;
		border-color: var(--primary, #3b82f6);
	}

	.help-text {
		font-size: 0.813rem;
		color: var(--text-secondary);
		margin: 0 0 0.75rem;
		line-height: 1.5;
	}

	.context-info {
		background: var(--bg-tertiary);
		border-radius: 6px;
		padding: 0.75rem;
	}

	.context-example {
		display: block;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.75rem;
		color: var(--text-primary);
		white-space: pre;
		overflow-x: auto;
	}

	.context-hint {
		margin: 0.75rem 0 0;
		font-size: 0.75rem;
		color: var(--text-secondary);
	}

	.context-hint code {
		background: var(--bg-primary);
		padding: 0.125rem 0.375rem;
		border-radius: 3px;
		font-size: 0.75rem;
	}

	.tips-list {
		margin: 0;
		padding: 0 0 0 1.25rem;
		font-size: 0.813rem;
		color: var(--text-secondary);
		line-height: 1.75;
	}

	.tips-list code {
		background: var(--bg-tertiary);
		padding: 0.125rem 0.375rem;
		border-radius: 3px;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.75rem;
	}

	/* Actions */
	.actions {
		display: flex;
		gap: 0.75rem;
	}

	.btn {
		padding: 0.625rem 1.25rem;
		border-radius: 6px;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		border: 1px solid transparent;
		transition: all 0.15s ease;
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-primary {
		background: var(--primary, #3b82f6);
		color: white;
	}

	.btn-primary:hover:not(:disabled) {
		background: var(--primary-hover, #2563eb);
	}

	.btn-secondary {
		background: transparent;
		border-color: var(--border-color);
		color: var(--text-primary);
	}

	.btn-secondary:hover:not(:disabled) {
		background: var(--bg-tertiary);
	}

	/* Current Config */
	.current-config {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		padding: 1rem;
	}

	.current-config h3 {
		margin: 0 0 0.75rem;
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--text-secondary);
	}

	.config-detail {
		display: flex;
		gap: 0.5rem;
		font-size: 0.813rem;
		margin-bottom: 0.5rem;
	}

	.config-detail:last-child {
		margin-bottom: 0;
	}

	.detail-label {
		color: var(--text-secondary);
		min-width: 70px;
	}

	.command-value {
		word-break: break-all;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		font-size: 0.75rem;
		background: var(--bg-tertiary);
		padding: 0.25rem 0.5rem;
		border-radius: 4px;
	}

	@media (max-width: 640px) {
		.presets-grid,
		.options-grid,
		.form-row {
			grid-template-columns: 1fr;
		}
	}
</style>
