import { useEffect, useState, useCallback, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { create } from '@bufbuild/protobuf';
import { WorkflowProgress } from '@/components/task-detail/WorkflowProgress';
import { TaskFooter } from '@/components/task-detail/TaskFooter';
import { SplitPane } from '@/components/core/SplitPane';
import { TranscriptTab } from '@/components/task-detail/TranscriptTab';
import { ChangesTabEnhanced } from '@/components/task-detail/ChangesTabEnhanced';
import { FeedbackPanel } from '@/components/task-detail/FeedbackPanel';
import { Icon } from '@/components/ui/Icon';
import { Button } from '@/components/ui/Button';
import { taskClient } from '@/lib/client';
import { toast } from '@/stores/uiStore';
import { useTaskSubscription, useDocumentTitle } from '@/hooks';
import { useTask as useStoreTask } from '@/stores/taskStore';
import { useCurrentProjectId, useTaskSessionMetrics } from '@/stores';
import type { Task, TaskPlan } from '@/gen/orc/v1/task_pb';
import {
	GetTaskRequestSchema,
	GetTaskPlanRequestSchema,
	RetryTaskRequestSchema,
	TaskStatus,
	PhaseStatus,
	UpdateTaskRequestSchema,
} from '@/gen/orc/v1/task_pb';
import type { InitiativeNote } from '@/gen/orc/v1/initiative_pb';
import { initiativeClient } from '@/lib/client';
import './TaskDetail.css';

/**
 * Format elapsed time since a timestamp
 */
function formatElapsedTime(startedAt: { seconds: bigint } | undefined): string {
	if (!startedAt) return '—';
	const startMs = Number(startedAt.seconds) * 1000;
	const elapsed = Date.now() - startMs;
	const totalSeconds = Math.floor(elapsed / 1000);
	const minutes = Math.floor(totalSeconds / 60);
	const seconds = totalSeconds % 60;
	return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

/**
 * Task detail page (/tasks/:id)
 *
 * New "deep work" layout with:
 * - Header with back link, task info, workflow, branch, elapsed time
 * - Workflow progress visualization
 * - Split pane (Live Output + Changes)
 * - Footer with metrics and action buttons
 */
export function TaskDetail() {
	const { id } = useParams<{ id: string }>();
	const projectId = useCurrentProjectId();

	// State
	const [task, setTask] = useState<Task | null>(null);
	const [plan, setPlan] = useState<TaskPlan | null>(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [elapsedTime, setElapsedTime] = useState('—');
	const [retryGuidance, setRetryGuidance] = useState('');
	const [retryFromPhase, setRetryFromPhase] = useState('');
	const [isRetrying, setIsRetrying] = useState(false);
	const [isFixingManually, setIsFixingManually] = useState(false);
	const [isAborting, setIsAborting] = useState(false);

	// Task-generated notes state
	const [generatedNotes, setGeneratedNotes] = useState<InitiativeNote[]>([]);
	const [notesExpanded, setNotesExpanded] = useState(true);

	// Set document title based on task
	useDocumentTitle(task ? `${task.id}: ${task.title}` : id);

	// Subscribe to real-time updates
	const { state: taskState, transcript: streamingTranscript } = useTaskSubscription(id);

	// Get task from store (updated by WebSocket events)
	const storeTask = useStoreTask(id ?? '');
	const liveSessionMetrics = useTaskSessionMetrics(id ?? '');

	// Sync local task state with store task when WebSocket updates arrive
	useEffect(() => {
		if (storeTask) {
			setTask((prev) => {
				if (prev) {
					return { ...prev, ...storeTask };
				}
				return storeTask;
			});
		}
	}, [storeTask]);

	// Load task data
	const loadTask = useCallback(async () => {
		if (!id || !projectId) return;

		setLoading(true);
		setError(null);

		try {
			const [taskResponse, planResponse] = await Promise.all([
				taskClient.getTask(create(GetTaskRequestSchema, { projectId, taskId: id })),
				taskClient.getTaskPlan(create(GetTaskPlanRequestSchema, { projectId, taskId: id })).catch(() => null),
			]);

			if (taskResponse.task) {
				setTask(taskResponse.task);
			}
			if (planResponse?.plan) {
				setPlan(planResponse.plan);
			}
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to load task');
		} finally {
			setLoading(false);
		}
	}, [id, projectId]);

	// Load notes generated by this task
	const loadGeneratedNotes = useCallback(async () => {
		if (!id || !projectId) return;
		try {
			const response = await initiativeClient.listTaskGeneratedNotes({
				projectId,
				taskId: id,
			});
			setGeneratedNotes(response.notes || []);
		} catch (e) {
			console.error('Failed to load task-generated notes:', e);
		}
	}, [id, projectId]);

	// Initial load
	useEffect(() => {
		loadTask();
	}, [loadTask]);

	// Load notes when task is loaded
	useEffect(() => {
		if (task) {
			loadGeneratedNotes();
		}
	}, [task, loadGeneratedNotes]);

	// Update elapsed time every second when task is running
	useEffect(() => {
		if (!task?.startedAt) return;

		// Initial update
		setElapsedTime(formatElapsedTime(task.startedAt));

		// Update every second
		const interval = setInterval(() => {
			setElapsedTime(formatElapsedTime(task.startedAt));
		}, 1000);

		return () => clearInterval(interval);
	}, [task?.startedAt]);

	// Handle task update (from footer actions)
	const handleTaskUpdate = useCallback((updatedTask: Task) => {
		setTask(updatedTask);
	}, []);

	const handleRetry = useCallback(
		async (fromPhase: string) => {
			if (!projectId || !id || !fromPhase) return;
			setIsRetrying(true);
			try {
				const result = await taskClient.retryTask(
					create(RetryTaskRequestSchema, {
						projectId,
						taskId: id,
						fromPhase,
						instructions: retryGuidance.trim() || undefined,
					})
				);
				if (result.task) {
					setTask(result.task);
				}
				setRetryGuidance('');
				toast.success('Task retry started');
			} catch (e) {
				toast.error(e instanceof Error ? e.message : 'Failed to retry task');
			} finally {
				setIsRetrying(false);
			}
		},
		[id, projectId, retryGuidance]
	);

	const handleFixManually = useCallback(async () => {
		if (!projectId || !id) return;
		setIsFixingManually(true);
		try {
			const result = await taskClient.updateTask(
				create(UpdateTaskRequestSchema, {
					projectId,
					taskId: id,
					status: TaskStatus.PAUSED,
					manualFix: true,
				})
			);
			if (result.task) {
				setTask(result.task);
			}
			toast.success('Task paused for manual fix');
		} catch (e) {
			toast.error(e instanceof Error ? e.message : 'Failed to pause task for manual fix');
		} finally {
			setIsFixingManually(false);
		}
	}, [id, projectId]);

	const handleAbortTask = useCallback(async () => {
		if (!projectId || !id) return;
		if (!window.confirm('Abort this task? This marks it as closed.')) return;

		setIsAborting(true);
		try {
			const result = await taskClient.updateTask(
				create(UpdateTaskRequestSchema, {
					projectId,
					taskId: id,
					status: TaskStatus.CLOSED,
				})
			);
			if (result.task) {
				setTask(result.task);
			}
			toast.success('Task closed');
		} catch (e) {
			toast.error(e instanceof Error ? e.message : 'Failed to close task');
		} finally {
			setIsAborting(false);
		}
	}, [id, projectId]);

	// Handle phase click from WorkflowProgress - scroll to transcript section
	const handlePhaseClick = useCallback((phaseName: string) => {
		// Find the transcript section with matching data-phase attribute
		const element = document.querySelector(`[data-phase="${CSS.escape(phaseName)}"]`);
		if (element) {
			element.scrollIntoView({ behavior: 'smooth', block: 'start' });
		}
	}, []);

	// Build metrics from task state
	const metrics = useMemo(() => {
		const useLiveMetrics =
			liveSessionMetrics &&
			(task?.status === TaskStatus.RUNNING || task?.status === TaskStatus.FINALIZING);

		if (useLiveMetrics) {
			return {
				tokens: liveSessionMetrics.totalTokens,
				cost: liveSessionMetrics.estimatedCostUSD,
				inputTokens: liveSessionMetrics.inputTokens,
				outputTokens: liveSessionMetrics.outputTokens,
			};
		}

		const executionTokens = task?.execution?.tokens;
		const executionCost = task?.execution?.cost;
		if (!executionTokens && !executionCost) {
			return null;
		}

		return {
			tokens: executionTokens?.totalTokens ?? 0,
			cost: executionCost?.totalCostUsd ?? 0,
			inputTokens: executionTokens?.inputTokens ?? 0,
			outputTokens: executionTokens?.outputTokens ?? 0,
		};
	}, [liveSessionMetrics, task]);

	const completedPhases = useMemo(() => {
		if (!plan) return [];
		return plan.phases.filter((phase) => phase.status === PhaseStatus.COMPLETED);
	}, [plan]);

	const failedPhase = task?.currentPhase ?? '';

	const errorMessage = useMemo(() => {
		if (!task?.currentPhase) {
			return task?.execution?.error ?? 'Task failed';
		}
		return (
			taskState?.phases[task.currentPhase]?.error ??
			task?.execution?.error ??
			'Task failed'
		);
	}, [task?.currentPhase, task?.execution?.error, taskState?.phases]);

	useEffect(() => {
		if (!completedPhases.length) {
			setRetryFromPhase('');
			return;
		}
		setRetryFromPhase((current) => {
			const hasCurrent = completedPhases.some((phase) => phase.name === current);
			if (hasCurrent) return current;
			return completedPhases[0]?.name ?? '';
		});
	}, [completedPhases]);

	// Loading state
	if (loading) {
		return (
			<div className="task-detail-page">
				<div className="task-detail-loading">
					<div className="loading-spinner" />
					<span>Loading task...</span>
				</div>
			</div>
		);
	}

	// Error state
	if (error || !task) {
		return (
			<div className="task-detail-page">
				<div className="task-detail-error">
					<Icon name="alert-circle" size={32} />
					<h2>Failed to load task</h2>
					<p>{error || 'Task not found'}</p>
					<Button variant="secondary" onClick={loadTask}>
						Retry
					</Button>
				</div>
			</div>
		);
	}

	return (
		<div className="task-detail-page">
			{/* Header */}
			<header className="task-detail-header">
				<div className="task-detail-header__top">
					<Link to="/board" className="task-detail-header__back">
						<Icon name="arrow-left" size={16} />
						Back to Board
					</Link>
					<div className="task-detail-header__info">
						<span className="task-detail-header__id">{task.id}</span>
						<h1 className="task-detail-header__title">{task.title}</h1>
					</div>
					<div className="task-detail-header__meta">
						{task.workflowId && (
							<span className="task-detail-header__workflow">
								<Icon name="workflow" size={14} />
								{task.workflowId}
							</span>
						)}
						{task.branch && (
							<span className="task-detail-header__branch">
								<Icon name="branch" size={14} />
								<code>{task.branch}</code>
							</span>
						)}
						<span className="task-detail-header__elapsed">
							<Icon name="clock" size={14} />
							{elapsedTime}
						</span>
					</div>
				</div>

				{/* Workflow Progress */}
				<WorkflowProgress task={task} plan={plan} onPhaseClick={handlePhaseClick} />
			</header>

			{/* Main content: Split pane */}
			<div className="task-detail-content">
				{task.status === TaskStatus.FAILED && (
					<section
						className="task-detail-error-panel"
						aria-label="Task failure details"
						data-testid="task-detail-error-panel"
					>
						<div className="task-detail-error-panel__header">
							<Icon name="alert-circle" size={18} />
							<div>
								<h2>
									Error in <code>{failedPhase || 'unknown phase'}</code>
								</h2>
								<p>{errorMessage}</p>
							</div>
						</div>

						<div className="task-detail-error-panel__details" role="region" aria-label="Error output">
							{errorMessage}
						</div>

						<div className="task-detail-error-panel__guidance">
							<label htmlFor="retry-guidance">Guidance for retry</label>
							<textarea
								id="retry-guidance"
								placeholder="Add guidance for the retry..."
								value={retryGuidance}
								onChange={(event) => setRetryGuidance(event.target.value)}
								rows={3}
							/>
						</div>

						<div className="task-detail-error-panel__actions">
							<Button
								variant="primary"
								onClick={() => handleRetry(failedPhase)}
								loading={isRetrying}
								disabled={!failedPhase || isFixingManually || isAborting}
								leftIcon={<Icon name="refresh" size={14} />}
							>
								Retry {failedPhase || 'phase'}
							</Button>

							<div className="task-detail-error-panel__retry-earlier">
								<select
									value={retryFromPhase}
									onChange={(event) => setRetryFromPhase(event.target.value)}
									aria-label="Retry from earlier phase"
									disabled={!completedPhases.length || isRetrying}
								>
									<option value="" disabled>
										Select phase
									</option>
									{completedPhases.map((phase) => (
										<option key={phase.id} value={phase.name}>
											{phase.name}
										</option>
									))}
								</select>
								<Button
									variant="secondary"
									onClick={() => handleRetry(retryFromPhase)}
									loading={isRetrying}
									disabled={!retryFromPhase || isFixingManually || isAborting}
								>
									Retry from earlier
								</Button>
							</div>

							<Button
								variant="secondary"
								onClick={handleFixManually}
								loading={isFixingManually}
								disabled={isRetrying || isAborting}
							>
								Fix Manually
							</Button>

							<Button
								variant="ghost"
								onClick={handleAbortTask}
								loading={isAborting}
								disabled={isRetrying || isFixingManually}
							>
								Abort Task
							</Button>
						</div>
					</section>
				)}

				<SplitPane
					left={
						<div className="task-detail-panel">
							<h2 className="task-detail-panel__title">Live Output</h2>
							<div className="task-detail-panel__content">
								<TranscriptTab
									taskId={task.id}
									streamingLines={streamingTranscript}
									currentPhase={task.currentPhase ?? undefined}
									isRunning={
										task.status === TaskStatus.RUNNING ||
										task.status === TaskStatus.FINALIZING
									}
								/>
							</div>
						</div>
					}
					right={
						<div className="task-detail-panel">
							<h2 className="task-detail-panel__title">Changes</h2>
							<div className="task-detail-panel__content">
								<ChangesTabEnhanced taskId={task.id} />
							</div>
						</div>
					}
					persistKey="task-detail"
					initialRatio={60}
					minLeftWidth={200}
					minRightWidth={200}
					leftEmptyMessage="No output yet"
					rightEmptyMessage="No changes yet"
				/>

				{/* Feedback Panel - shown for running tasks or when feedback is available */}
				{(task.status === TaskStatus.RUNNING || task.status === TaskStatus.PAUSED) && projectId && (
					<div className="task-detail-feedback">
						<FeedbackPanel
							task={task}
							onTaskUpdate={(updatedTask) => {
								// Task status updated via feedback (e.g., paused)
								setTask(updatedTask);
							}}
						/>
					</div>
				)}

				{/* Notes Generated Section - shown when task has generated notes */}
				{generatedNotes.length > 0 && (
					<div className="task-detail-notes">
						<div className="task-detail-notes__header">
							<h3>
								<Icon name="brain" size={16} />
								Notes Generated ({generatedNotes.length})
							</h3>
							<Button
								variant="ghost"
								size="sm"
								onClick={() => setNotesExpanded((prev) => !prev)}
								aria-expanded={notesExpanded}
							>
								<Icon name={notesExpanded ? 'chevron-up' : 'chevron-down'} size={16} />
							</Button>
						</div>
						{notesExpanded && (
							<div className="task-detail-notes__list">
								{generatedNotes.map((note) => (
									<div key={note.id} className="task-detail-note">
										<span className={`task-detail-note__type type-${note.noteType}`}>
											{note.noteType}
										</span>
										<p className="task-detail-note__content">{note.content}</p>
										{note.relevantFiles && note.relevantFiles.length > 0 && (
											<div className="task-detail-note__files">
												{note.relevantFiles.map((file, idx) => (
													<code key={idx}>{file}</code>
												))}
											</div>
										)}
									</div>
								))}
							</div>
						)}
					</div>
				)}
			</div>

			{/* Footer */}
			<TaskFooter
				task={task}
				metrics={metrics}
				onTaskUpdate={handleTaskUpdate}
			/>
		</div>
	);
}
