package db

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRemoveAutoGeneratedExecutors verifies that auto-generated executor-* agents
// are removed and phase templates no longer reference them.
func TestRemoveAutoGeneratedExecutors(t *testing.T) {
	// Create a project database that will run all migrations
	pdb, err := OpenProjectInMemory()
	require.NoError(t, err)
	defer func() { _ = pdb.Close() }()

	// Simulate pre-migration state by inserting auto-generated executor agents
	// This mimics what migration 045 created
	_, err = pdb.Exec(`
		INSERT INTO agents (id, name, description, prompt, tools, is_builtin)
		VALUES 
			('executor-spec', 'Specification-executor', 'Executor agent for Specification phase', '', '[]', 1),
			('executor-implement', 'Implementation-executor', 'Executor agent for Implementation phase', '', '[]', 1),
			('executor-review', 'Review-executor', 'Executor agent for Review phase', '', '[]', 1)
	`)
	require.NoError(t, err)

	// Create phase templates that reference these executor agents
	_, err = pdb.Exec(`
		INSERT INTO phase_templates (id, name, agent_id, is_builtin)
		VALUES 
			('spec', 'Specification', 'executor-spec', 1),
			('implement', 'Implementation', 'executor-implement', 1),
			('review', 'Review', 'executor-review', 1)
		ON CONFLICT(id) DO UPDATE SET agent_id = excluded.agent_id
	`)
	require.NoError(t, err)

	// Also insert a real agent that should NOT be deleted
	_, err = pdb.Exec(`
		INSERT INTO agents (id, name, description, prompt, tools, is_builtin)
		VALUES ('code-reviewer', 'Code Reviewer', 'Reviews code for issues', 'Review the code', '["Read","Grep"]', 1)
	`)
	require.NoError(t, err)

	// Verify data was inserted into underlying storage (even though VIEW filters it)
	// Note: The agents VIEW filters out executor-* pattern, so querying the view returns 0.
	// This is correct behavior - executor-* agents are hidden from normal queries.
	var executorCount int
	err = pdb.QueryRow(`SELECT COUNT(*) FROM _agents_storage WHERE id LIKE 'executor-%'`).Scan(&executorCount)
	require.NoError(t, err)
	assert.Equal(t, 3, executorCount, "should have 3 executor-* agents in storage")

	// SC-1: After migration, no agents should have 'executor-*' pattern IDs
	var postMigrationExecutorCount int
	err = pdb.QueryRow(`SELECT COUNT(*) FROM agents WHERE id LIKE 'executor-%'`).Scan(&postMigrationExecutorCount)
	require.NoError(t, err)
	assert.Equal(t, 0, postMigrationExecutorCount, "SC-1: no agents should have executor-* IDs after migration")

	// SC-2: Real agents should still exist
	realAgent, err := pdb.GetAgent("code-reviewer")
	require.NoError(t, err)
	assert.NotNil(t, realAgent, "SC-2: real agents should still exist after migration")

	// SC-3: Phase templates should have NULL agent_id (not referencing executor-*)
	var specAgentID *string
	err = pdb.QueryRow(`SELECT agent_id FROM phase_templates WHERE id = 'spec'`).Scan(&specAgentID)
	require.NoError(t, err)
	assert.Nil(t, specAgentID, "SC-3: phase template agent_id should be NULL after migration")
}

// TestExecutorAgentPatternDeleted verifies the exact deletion pattern
func TestExecutorAgentPatternDeleted(t *testing.T) {
	pdb, err := OpenProjectInMemory()
	require.NoError(t, err)
	defer func() { _ = pdb.Close() }()

	// Insert various agent patterns
	_, err = pdb.Exec(`
		INSERT INTO agents (id, name, description, prompt, tools, is_builtin)
		VALUES 
			('executor-spec', 'Spec Executor', 'desc', '', '[]', 1),
			('my-executor', 'Custom Executor', 'desc', '', '[]', 0),
			('executor-impl', 'Impl Executor', 'desc', '', '[]', 1)
	`)
	require.NoError(t, err)

	// After migration, only 'executor-*' pattern should be deleted
	// 'my-executor' should remain (doesn't match 'executor-%' pattern)
	var myExecutor *Agent
	myExecutor, err = pdb.GetAgent("my-executor")
	require.NoError(t, err)
	assert.NotNil(t, myExecutor, "'my-executor' should remain - doesn't match 'executor-%' pattern")

	// executor-spec and executor-impl should be gone
	specExecutor, err := pdb.GetAgent("executor-spec")
	require.NoError(t, err)
	assert.Nil(t, specExecutor, "'executor-spec' should be deleted")

	implExecutor, err := pdb.GetAgent("executor-impl")
	require.NoError(t, err)
	assert.Nil(t, implExecutor, "'executor-impl' should be deleted")
}
